#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsis.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertDUYURULAR(DUYURULAR instance);
    partial void UpdateDUYURULAR(DUYURULAR instance);
    partial void DeleteDUYURULAR(DUYURULAR instance);
    partial void InsertGALERI_RESIMLERI(GALERI_RESIMLERI instance);
    partial void UpdateGALERI_RESIMLERI(GALERI_RESIMLERI instance);
    partial void DeleteGALERI_RESIMLERI(GALERI_RESIMLERI instance);
    partial void InsertGALERILER(GALERILER instance);
    partial void UpdateGALERILER(GALERILER instance);
    partial void DeleteGALERILER(GALERILER instance);
    partial void InsertHABERLER(HABERLER instance);
    partial void UpdateHABERLER(HABERLER instance);
    partial void DeleteHABERLER(HABERLER instance);
    partial void InsertICERIK(ICERIK instance);
    partial void UpdateICERIK(ICERIK instance);
    partial void DeleteICERIK(ICERIK instance);
    partial void InsertILETISIM_BILGILERI(ILETISIM_BILGILERI instance);
    partial void UpdateILETISIM_BILGILERI(ILETISIM_BILGILERI instance);
    partial void DeleteILETISIM_BILGILERI(ILETISIM_BILGILERI instance);
    partial void InsertILETISIM_FORMLARI(ILETISIM_FORMLARI instance);
    partial void UpdateILETISIM_FORMLARI(ILETISIM_FORMLARI instance);
    partial void DeleteILETISIM_FORMLARI(ILETISIM_FORMLARI instance);
    partial void InsertIS_BASVURULARI(IS_BASVURULARI instance);
    partial void UpdateIS_BASVURULARI(IS_BASVURULARI instance);
    partial void DeleteIS_BASVURULARI(IS_BASVURULARI instance);
    partial void InsertKATEGORILER(KATEGORILER instance);
    partial void UpdateKATEGORILER(KATEGORILER instance);
    partial void DeleteKATEGORILER(KATEGORILER instance);
    partial void InsertKATILIMCI_GORUSLERI(KATILIMCI_GORUSLERI instance);
    partial void UpdateKATILIMCI_GORUSLERI(KATILIMCI_GORUSLERI instance);
    partial void DeleteKATILIMCI_GORUSLERI(KATILIMCI_GORUSLERI instance);
    partial void InsertMANSET(MANSET instance);
    partial void UpdateMANSET(MANSET instance);
    partial void DeleteMANSET(MANSET instance);
    partial void InsertREFERANSLAR(REFERANSLAR instance);
    partial void UpdateREFERANSLAR(REFERANSLAR instance);
    partial void DeleteREFERANSLAR(REFERANSLAR instance);
    partial void InsertRESIM_AYAR(RESIM_AYAR instance);
    partial void UpdateRESIM_AYAR(RESIM_AYAR instance);
    partial void DeleteRESIM_AYAR(RESIM_AYAR instance);
    partial void InsertSITE_BILGILERI(SITE_BILGILERI instance);
    partial void UpdateSITE_BILGILERI(SITE_BILGILERI instance);
    partial void DeleteSITE_BILGILERI(SITE_BILGILERI instance);
    partial void InsertSOSYAL_MEDYA(SOSYAL_MEDYA instance);
    partial void UpdateSOSYAL_MEDYA(SOSYAL_MEDYA instance);
    partial void DeleteSOSYAL_MEDYA(SOSYAL_MEDYA instance);
    partial void InsertTEMALAR(TEMALAR instance);
    partial void UpdateTEMALAR(TEMALAR instance);
    partial void DeleteTEMALAR(TEMALAR instance);
    partial void InsertURUN_KATEGORILERI(URUN_KATEGORILERI instance);
    partial void UpdateURUN_KATEGORILERI(URUN_KATEGORILERI instance);
    partial void DeleteURUN_KATEGORILERI(URUN_KATEGORILERI instance);
    partial void InsertURUNLER(URUNLER instance);
    partial void UpdateURUNLER(URUNLER instance);
    partial void DeleteURUNLER(URUNLER instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<DUYURULAR> DUYURULARs
		{
			get
			{
				return this.GetTable<DUYURULAR>();
			}
		}
		
		public System.Data.Linq.Table<GALERI_RESIMLERI> GALERI_RESIMLERIs
		{
			get
			{
				return this.GetTable<GALERI_RESIMLERI>();
			}
		}
		
		public System.Data.Linq.Table<GALERILER> GALERILERs
		{
			get
			{
				return this.GetTable<GALERILER>();
			}
		}
		
		public System.Data.Linq.Table<HABERLER> HABERLERs
		{
			get
			{
				return this.GetTable<HABERLER>();
			}
		}
		
		public System.Data.Linq.Table<ICERIK> ICERIKs
		{
			get
			{
				return this.GetTable<ICERIK>();
			}
		}
		
		public System.Data.Linq.Table<ILETISIM_BILGILERI> ILETISIM_BILGILERIs
		{
			get
			{
				return this.GetTable<ILETISIM_BILGILERI>();
			}
		}
		
		public System.Data.Linq.Table<ILETISIM_FORMLARI> ILETISIM_FORMLARIs
		{
			get
			{
				return this.GetTable<ILETISIM_FORMLARI>();
			}
		}
		
		public System.Data.Linq.Table<IS_BASVURULARI> IS_BASVURULARIs
		{
			get
			{
				return this.GetTable<IS_BASVURULARI>();
			}
		}
		
		public System.Data.Linq.Table<KATEGORILER> KATEGORILERs
		{
			get
			{
				return this.GetTable<KATEGORILER>();
			}
		}
		
		public System.Data.Linq.Table<KATILIMCI_GORUSLERI> KATILIMCI_GORUSLERIs
		{
			get
			{
				return this.GetTable<KATILIMCI_GORUSLERI>();
			}
		}
		
		public System.Data.Linq.Table<MANSET> MANSETs
		{
			get
			{
				return this.GetTable<MANSET>();
			}
		}
		
		public System.Data.Linq.Table<REFERANSLAR> REFERANSLARs
		{
			get
			{
				return this.GetTable<REFERANSLAR>();
			}
		}
		
		public System.Data.Linq.Table<RESIM_AYAR> RESIM_AYARs
		{
			get
			{
				return this.GetTable<RESIM_AYAR>();
			}
		}
		
		public System.Data.Linq.Table<SITE_BILGILERI> SITE_BILGILERIs
		{
			get
			{
				return this.GetTable<SITE_BILGILERI>();
			}
		}
		
		public System.Data.Linq.Table<SOSYAL_MEDYA> SOSYAL_MEDYAs
		{
			get
			{
				return this.GetTable<SOSYAL_MEDYA>();
			}
		}
		
		public System.Data.Linq.Table<TEMALAR> TEMALARs
		{
			get
			{
				return this.GetTable<TEMALAR>();
			}
		}
		
		public System.Data.Linq.Table<URUN_KATEGORILERI> URUN_KATEGORILERIs
		{
			get
			{
				return this.GetTable<URUN_KATEGORILERI>();
			}
		}
		
		public System.Data.Linq.Table<URUNLER> URUNLERs
		{
			get
			{
				return this.GetTable<URUNLER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KULLANICI_ADI;
		
		private string _SIFRE;
		
		private System.Nullable<bool> _DURUM;
		
		private System.Nullable<int> _SEVIYE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKULLANICI_ADIChanging(string value);
    partial void OnKULLANICI_ADIChanged();
    partial void OnSIFREChanging(string value);
    partial void OnSIFREChanged();
    partial void OnDURUMChanging(System.Nullable<bool> value);
    partial void OnDURUMChanged();
    partial void OnSEVIYEChanging(System.Nullable<int> value);
    partial void OnSEVIYEChanged();
    #endregion
		
		public ADMIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KULLANICI_ADI", DbType="VarChar(50)")]
		public string KULLANICI_ADI
		{
			get
			{
				return this._KULLANICI_ADI;
			}
			set
			{
				if ((this._KULLANICI_ADI != value))
				{
					this.OnKULLANICI_ADIChanging(value);
					this.SendPropertyChanging();
					this._KULLANICI_ADI = value;
					this.SendPropertyChanged("KULLANICI_ADI");
					this.OnKULLANICI_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIFRE", DbType="VarChar(50)")]
		public string SIFRE
		{
			get
			{
				return this._SIFRE;
			}
			set
			{
				if ((this._SIFRE != value))
				{
					this.OnSIFREChanging(value);
					this.SendPropertyChanging();
					this._SIFRE = value;
					this.SendPropertyChanged("SIFRE");
					this.OnSIFREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURUM", DbType="Bit")]
		public System.Nullable<bool> DURUM
		{
			get
			{
				return this._DURUM;
			}
			set
			{
				if ((this._DURUM != value))
				{
					this.OnDURUMChanging(value);
					this.SendPropertyChanging();
					this._DURUM = value;
					this.SendPropertyChanged("DURUM");
					this.OnDURUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEVIYE", DbType="Int")]
		public System.Nullable<int> SEVIYE
		{
			get
			{
				return this._SEVIYE;
			}
			set
			{
				if ((this._SEVIYE != value))
				{
					this.OnSEVIYEChanging(value);
					this.SendPropertyChanging();
					this._SEVIYE = value;
					this.SendPropertyChanged("SEVIYE");
					this.OnSEVIYEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DUYURULAR")]
	public partial class DUYURULAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _BASLIK;
		
		private string _DUYURU;
		
		private System.Nullable<System.DateTime> _TARIH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBASLIKChanging(string value);
    partial void OnBASLIKChanged();
    partial void OnDUYURUChanging(string value);
    partial void OnDUYURUChanged();
    partial void OnTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnTARIHChanged();
    #endregion
		
		public DUYURULAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BASLIK", DbType="VarChar(250)")]
		public string BASLIK
		{
			get
			{
				return this._BASLIK;
			}
			set
			{
				if ((this._BASLIK != value))
				{
					this.OnBASLIKChanging(value);
					this.SendPropertyChanging();
					this._BASLIK = value;
					this.SendPropertyChanged("BASLIK");
					this.OnBASLIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUYURU", DbType="VarChar(MAX)")]
		public string DUYURU
		{
			get
			{
				return this._DUYURU;
			}
			set
			{
				if ((this._DUYURU != value))
				{
					this.OnDUYURUChanging(value);
					this.SendPropertyChanging();
					this._DUYURU = value;
					this.SendPropertyChanged("DUYURU");
					this.OnDUYURUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARIH
		{
			get
			{
				return this._TARIH;
			}
			set
			{
				if ((this._TARIH != value))
				{
					this.OnTARIHChanging(value);
					this.SendPropertyChanging();
					this._TARIH = value;
					this.SendPropertyChanged("TARIH");
					this.OnTARIHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GALERI_RESIMLERI")]
	public partial class GALERI_RESIMLERI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _GALERI_ID;
		
		private string _ACIKLAMA;
		
		private string _RESIM;
		
		private System.Nullable<int> _SIRA_NO;
		
		private string _TITLE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGALERI_IDChanging(System.Nullable<int> value);
    partial void OnGALERI_IDChanged();
    partial void OnACIKLAMAChanging(string value);
    partial void OnACIKLAMAChanged();
    partial void OnRESIMChanging(string value);
    partial void OnRESIMChanged();
    partial void OnSIRA_NOChanging(System.Nullable<int> value);
    partial void OnSIRA_NOChanged();
    partial void OnTITLEChanging(string value);
    partial void OnTITLEChanged();
    #endregion
		
		public GALERI_RESIMLERI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GALERI_ID", DbType="Int")]
		public System.Nullable<int> GALERI_ID
		{
			get
			{
				return this._GALERI_ID;
			}
			set
			{
				if ((this._GALERI_ID != value))
				{
					this.OnGALERI_IDChanging(value);
					this.SendPropertyChanging();
					this._GALERI_ID = value;
					this.SendPropertyChanged("GALERI_ID");
					this.OnGALERI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="VarChar(250)")]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this.OnACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACIKLAMA = value;
					this.SendPropertyChanged("ACIKLAMA");
					this.OnACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESIM", DbType="VarChar(150)")]
		public string RESIM
		{
			get
			{
				return this._RESIM;
			}
			set
			{
				if ((this._RESIM != value))
				{
					this.OnRESIMChanging(value);
					this.SendPropertyChanging();
					this._RESIM = value;
					this.SendPropertyChanged("RESIM");
					this.OnRESIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIRA_NO", DbType="Int")]
		public System.Nullable<int> SIRA_NO
		{
			get
			{
				return this._SIRA_NO;
			}
			set
			{
				if ((this._SIRA_NO != value))
				{
					this.OnSIRA_NOChanging(value);
					this.SendPropertyChanging();
					this._SIRA_NO = value;
					this.SendPropertyChanged("SIRA_NO");
					this.OnSIRA_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="VarChar(250)")]
		public string TITLE
		{
			get
			{
				return this._TITLE;
			}
			set
			{
				if ((this._TITLE != value))
				{
					this.OnTITLEChanging(value);
					this.SendPropertyChanging();
					this._TITLE = value;
					this.SendPropertyChanged("TITLE");
					this.OnTITLEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GALERILER")]
	public partial class GALERILER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GALERI_ADI;
		
		private string _KEYWORDS;
		
		private string _DESCRIPTION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGALERI_ADIChanging(string value);
    partial void OnGALERI_ADIChanged();
    partial void OnKEYWORDSChanging(string value);
    partial void OnKEYWORDSChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    #endregion
		
		public GALERILER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GALERI_ADI", DbType="VarChar(50)")]
		public string GALERI_ADI
		{
			get
			{
				return this._GALERI_ADI;
			}
			set
			{
				if ((this._GALERI_ADI != value))
				{
					this.OnGALERI_ADIChanging(value);
					this.SendPropertyChanging();
					this._GALERI_ADI = value;
					this.SendPropertyChanged("GALERI_ADI");
					this.OnGALERI_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEYWORDS", DbType="VarChar(250)")]
		public string KEYWORDS
		{
			get
			{
				return this._KEYWORDS;
			}
			set
			{
				if ((this._KEYWORDS != value))
				{
					this.OnKEYWORDSChanging(value);
					this.SendPropertyChanging();
					this._KEYWORDS = value;
					this.SendPropertyChanged("KEYWORDS");
					this.OnKEYWORDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="VarChar(250)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HABERLER")]
	public partial class HABERLER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _BASLIK;
		
		private string _ICERIK;
		
		private System.Nullable<System.DateTime> _TARIH;
		
		private string _RESIM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBASLIKChanging(string value);
    partial void OnBASLIKChanged();
    partial void OnICERIKChanging(string value);
    partial void OnICERIKChanged();
    partial void OnTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnTARIHChanged();
    partial void OnRESIMChanging(string value);
    partial void OnRESIMChanged();
    #endregion
		
		public HABERLER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BASLIK", DbType="VarChar(250)")]
		public string BASLIK
		{
			get
			{
				return this._BASLIK;
			}
			set
			{
				if ((this._BASLIK != value))
				{
					this.OnBASLIKChanging(value);
					this.SendPropertyChanging();
					this._BASLIK = value;
					this.SendPropertyChanged("BASLIK");
					this.OnBASLIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICERIK", DbType="VarChar(MAX)")]
		public string ICERIK
		{
			get
			{
				return this._ICERIK;
			}
			set
			{
				if ((this._ICERIK != value))
				{
					this.OnICERIKChanging(value);
					this.SendPropertyChanging();
					this._ICERIK = value;
					this.SendPropertyChanged("ICERIK");
					this.OnICERIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARIH
		{
			get
			{
				return this._TARIH;
			}
			set
			{
				if ((this._TARIH != value))
				{
					this.OnTARIHChanging(value);
					this.SendPropertyChanging();
					this._TARIH = value;
					this.SendPropertyChanged("TARIH");
					this.OnTARIHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESIM", DbType="VarChar(100)")]
		public string RESIM
		{
			get
			{
				return this._RESIM;
			}
			set
			{
				if ((this._RESIM != value))
				{
					this.OnRESIMChanging(value);
					this.SendPropertyChanging();
					this._RESIM = value;
					this.SendPropertyChanged("RESIM");
					this.OnRESIMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ICERIK")]
	public partial class ICERIK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ICERIK1;
		
		private string _TITLE;
		
		private string _KEYWORDS;
		
		private string _DESCRIPTION;
		
		private System.Nullable<int> _MENU_ID;
		
		private System.Nullable<int> _SAYFA_NO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnICERIK1Changing(string value);
    partial void OnICERIK1Changed();
    partial void OnTITLEChanging(string value);
    partial void OnTITLEChanged();
    partial void OnKEYWORDSChanging(string value);
    partial void OnKEYWORDSChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnMENU_IDChanging(System.Nullable<int> value);
    partial void OnMENU_IDChanged();
    partial void OnSAYFA_NOChanging(System.Nullable<int> value);
    partial void OnSAYFA_NOChanged();
    #endregion
		
		public ICERIK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ICERIK", Storage="_ICERIK1", DbType="VarChar(MAX)")]
		public string ICERIK1
		{
			get
			{
				return this._ICERIK1;
			}
			set
			{
				if ((this._ICERIK1 != value))
				{
					this.OnICERIK1Changing(value);
					this.SendPropertyChanging();
					this._ICERIK1 = value;
					this.SendPropertyChanged("ICERIK1");
					this.OnICERIK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="VarChar(250)")]
		public string TITLE
		{
			get
			{
				return this._TITLE;
			}
			set
			{
				if ((this._TITLE != value))
				{
					this.OnTITLEChanging(value);
					this.SendPropertyChanging();
					this._TITLE = value;
					this.SendPropertyChanged("TITLE");
					this.OnTITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEYWORDS", DbType="VarChar(250)")]
		public string KEYWORDS
		{
			get
			{
				return this._KEYWORDS;
			}
			set
			{
				if ((this._KEYWORDS != value))
				{
					this.OnKEYWORDSChanging(value);
					this.SendPropertyChanging();
					this._KEYWORDS = value;
					this.SendPropertyChanged("KEYWORDS");
					this.OnKEYWORDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="VarChar(250)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_ID", DbType="Int")]
		public System.Nullable<int> MENU_ID
		{
			get
			{
				return this._MENU_ID;
			}
			set
			{
				if ((this._MENU_ID != value))
				{
					this.OnMENU_IDChanging(value);
					this.SendPropertyChanging();
					this._MENU_ID = value;
					this.SendPropertyChanged("MENU_ID");
					this.OnMENU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAYFA_NO", DbType="Int")]
		public System.Nullable<int> SAYFA_NO
		{
			get
			{
				return this._SAYFA_NO;
			}
			set
			{
				if ((this._SAYFA_NO != value))
				{
					this.OnSAYFA_NOChanging(value);
					this.SendPropertyChanging();
					this._SAYFA_NO = value;
					this.SendPropertyChanged("SAYFA_NO");
					this.OnSAYFA_NOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ILETISIM_BILGILERI")]
	public partial class ILETISIM_BILGILERI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ADRES;
		
		private string _TEL1;
		
		private string _TEL2;
		
		private string _GSM;
		
		private string _FAX;
		
		private string _MAIL1;
		
		private string _MAIL2;
		
		private string _IL;
		
		private string _ILCE;
		
		private string _YER;
		
		private string _ENLEM;
		
		private string _BOYLAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnADRESChanging(string value);
    partial void OnADRESChanged();
    partial void OnTEL1Changing(string value);
    partial void OnTEL1Changed();
    partial void OnTEL2Changing(string value);
    partial void OnTEL2Changed();
    partial void OnGSMChanging(string value);
    partial void OnGSMChanged();
    partial void OnFAXChanging(string value);
    partial void OnFAXChanged();
    partial void OnMAIL1Changing(string value);
    partial void OnMAIL1Changed();
    partial void OnMAIL2Changing(string value);
    partial void OnMAIL2Changed();
    partial void OnILChanging(string value);
    partial void OnILChanged();
    partial void OnILCEChanging(string value);
    partial void OnILCEChanged();
    partial void OnYERChanging(string value);
    partial void OnYERChanged();
    partial void OnENLEMChanging(string value);
    partial void OnENLEMChanged();
    partial void OnBOYLAMChanging(string value);
    partial void OnBOYLAMChanged();
    #endregion
		
		public ILETISIM_BILGILERI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRES", DbType="VarChar(250)")]
		public string ADRES
		{
			get
			{
				return this._ADRES;
			}
			set
			{
				if ((this._ADRES != value))
				{
					this.OnADRESChanging(value);
					this.SendPropertyChanging();
					this._ADRES = value;
					this.SendPropertyChanged("ADRES");
					this.OnADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEL1", DbType="VarChar(50)")]
		public string TEL1
		{
			get
			{
				return this._TEL1;
			}
			set
			{
				if ((this._TEL1 != value))
				{
					this.OnTEL1Changing(value);
					this.SendPropertyChanging();
					this._TEL1 = value;
					this.SendPropertyChanged("TEL1");
					this.OnTEL1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEL2", DbType="VarChar(50)")]
		public string TEL2
		{
			get
			{
				return this._TEL2;
			}
			set
			{
				if ((this._TEL2 != value))
				{
					this.OnTEL2Changing(value);
					this.SendPropertyChanging();
					this._TEL2 = value;
					this.SendPropertyChanged("TEL2");
					this.OnTEL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSM", DbType="VarChar(50)")]
		public string GSM
		{
			get
			{
				return this._GSM;
			}
			set
			{
				if ((this._GSM != value))
				{
					this.OnGSMChanging(value);
					this.SendPropertyChanging();
					this._GSM = value;
					this.SendPropertyChanged("GSM");
					this.OnGSMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX", DbType="VarChar(50)")]
		public string FAX
		{
			get
			{
				return this._FAX;
			}
			set
			{
				if ((this._FAX != value))
				{
					this.OnFAXChanging(value);
					this.SendPropertyChanging();
					this._FAX = value;
					this.SendPropertyChanged("FAX");
					this.OnFAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAIL1", DbType="VarChar(50)")]
		public string MAIL1
		{
			get
			{
				return this._MAIL1;
			}
			set
			{
				if ((this._MAIL1 != value))
				{
					this.OnMAIL1Changing(value);
					this.SendPropertyChanging();
					this._MAIL1 = value;
					this.SendPropertyChanged("MAIL1");
					this.OnMAIL1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAIL2", DbType="VarChar(50)")]
		public string MAIL2
		{
			get
			{
				return this._MAIL2;
			}
			set
			{
				if ((this._MAIL2 != value))
				{
					this.OnMAIL2Changing(value);
					this.SendPropertyChanging();
					this._MAIL2 = value;
					this.SendPropertyChanged("MAIL2");
					this.OnMAIL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IL", DbType="VarChar(50)")]
		public string IL
		{
			get
			{
				return this._IL;
			}
			set
			{
				if ((this._IL != value))
				{
					this.OnILChanging(value);
					this.SendPropertyChanging();
					this._IL = value;
					this.SendPropertyChanged("IL");
					this.OnILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ILCE", DbType="VarChar(50)")]
		public string ILCE
		{
			get
			{
				return this._ILCE;
			}
			set
			{
				if ((this._ILCE != value))
				{
					this.OnILCEChanging(value);
					this.SendPropertyChanging();
					this._ILCE = value;
					this.SendPropertyChanged("ILCE");
					this.OnILCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YER", DbType="VarChar(150)")]
		public string YER
		{
			get
			{
				return this._YER;
			}
			set
			{
				if ((this._YER != value))
				{
					this.OnYERChanging(value);
					this.SendPropertyChanging();
					this._YER = value;
					this.SendPropertyChanged("YER");
					this.OnYERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENLEM", DbType="VarChar(50)")]
		public string ENLEM
		{
			get
			{
				return this._ENLEM;
			}
			set
			{
				if ((this._ENLEM != value))
				{
					this.OnENLEMChanging(value);
					this.SendPropertyChanging();
					this._ENLEM = value;
					this.SendPropertyChanged("ENLEM");
					this.OnENLEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOYLAM", DbType="VarChar(50)")]
		public string BOYLAM
		{
			get
			{
				return this._BOYLAM;
			}
			set
			{
				if ((this._BOYLAM != value))
				{
					this.OnBOYLAMChanging(value);
					this.SendPropertyChanging();
					this._BOYLAM = value;
					this.SendPropertyChanged("BOYLAM");
					this.OnBOYLAMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ILETISIM_FORMLARI")]
	public partial class ILETISIM_FORMLARI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _AD_SOYAD;
		
		private string _MAIL;
		
		private string _GSM;
		
		private string _KONU;
		
		private string _MESAJ;
		
		private System.Nullable<System.DateTime> _TARIH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAD_SOYADChanging(string value);
    partial void OnAD_SOYADChanged();
    partial void OnMAILChanging(string value);
    partial void OnMAILChanged();
    partial void OnGSMChanging(string value);
    partial void OnGSMChanged();
    partial void OnKONUChanging(string value);
    partial void OnKONUChanged();
    partial void OnMESAJChanging(string value);
    partial void OnMESAJChanged();
    partial void OnTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnTARIHChanged();
    #endregion
		
		public ILETISIM_FORMLARI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AD_SOYAD", DbType="VarChar(50)")]
		public string AD_SOYAD
		{
			get
			{
				return this._AD_SOYAD;
			}
			set
			{
				if ((this._AD_SOYAD != value))
				{
					this.OnAD_SOYADChanging(value);
					this.SendPropertyChanging();
					this._AD_SOYAD = value;
					this.SendPropertyChanged("AD_SOYAD");
					this.OnAD_SOYADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAIL", DbType="VarChar(50)")]
		public string MAIL
		{
			get
			{
				return this._MAIL;
			}
			set
			{
				if ((this._MAIL != value))
				{
					this.OnMAILChanging(value);
					this.SendPropertyChanging();
					this._MAIL = value;
					this.SendPropertyChanged("MAIL");
					this.OnMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSM", DbType="VarChar(50)")]
		public string GSM
		{
			get
			{
				return this._GSM;
			}
			set
			{
				if ((this._GSM != value))
				{
					this.OnGSMChanging(value);
					this.SendPropertyChanging();
					this._GSM = value;
					this.SendPropertyChanged("GSM");
					this.OnGSMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONU", DbType="VarChar(350)")]
		public string KONU
		{
			get
			{
				return this._KONU;
			}
			set
			{
				if ((this._KONU != value))
				{
					this.OnKONUChanging(value);
					this.SendPropertyChanging();
					this._KONU = value;
					this.SendPropertyChanged("KONU");
					this.OnKONUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESAJ", DbType="VarChar(MAX)")]
		public string MESAJ
		{
			get
			{
				return this._MESAJ;
			}
			set
			{
				if ((this._MESAJ != value))
				{
					this.OnMESAJChanging(value);
					this.SendPropertyChanging();
					this._MESAJ = value;
					this.SendPropertyChanged("MESAJ");
					this.OnMESAJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARIH
		{
			get
			{
				return this._TARIH;
			}
			set
			{
				if ((this._TARIH != value))
				{
					this.OnTARIHChanging(value);
					this.SendPropertyChanging();
					this._TARIH = value;
					this.SendPropertyChanged("TARIH");
					this.OnTARIHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IS_BASVURULARI")]
	public partial class IS_BASVURULARI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DOSYA_ADI;
		
		private System.Nullable<System.DateTime> _TARIH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDOSYA_ADIChanging(string value);
    partial void OnDOSYA_ADIChanged();
    partial void OnTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnTARIHChanged();
    #endregion
		
		public IS_BASVURULARI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSYA_ADI", DbType="VarChar(150)")]
		public string DOSYA_ADI
		{
			get
			{
				return this._DOSYA_ADI;
			}
			set
			{
				if ((this._DOSYA_ADI != value))
				{
					this.OnDOSYA_ADIChanging(value);
					this.SendPropertyChanging();
					this._DOSYA_ADI = value;
					this.SendPropertyChanged("DOSYA_ADI");
					this.OnDOSYA_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARIH
		{
			get
			{
				return this._TARIH;
			}
			set
			{
				if ((this._TARIH != value))
				{
					this.OnTARIHChanging(value);
					this.SendPropertyChanging();
					this._TARIH = value;
					this.SendPropertyChanged("TARIH");
					this.OnTARIHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KATEGORILER")]
	public partial class KATEGORILER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KATEGORI_ADI;
		
		private System.Nullable<int> _UST_KATEGORI_ID;
		
		private System.Nullable<bool> _DURUM;
		
		private string _URL;
		
		private System.Nullable<bool> _SILME_IZNI;
		
		private System.Nullable<int> _SIRA_NO;
		
		private System.Nullable<bool> _UST_MENU;
		
		private System.Nullable<bool> _ICERIK;
		
		private System.Nullable<int> _SAYFA_NO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKATEGORI_ADIChanging(string value);
    partial void OnKATEGORI_ADIChanged();
    partial void OnUST_KATEGORI_IDChanging(System.Nullable<int> value);
    partial void OnUST_KATEGORI_IDChanged();
    partial void OnDURUMChanging(System.Nullable<bool> value);
    partial void OnDURUMChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnSILME_IZNIChanging(System.Nullable<bool> value);
    partial void OnSILME_IZNIChanged();
    partial void OnSIRA_NOChanging(System.Nullable<int> value);
    partial void OnSIRA_NOChanged();
    partial void OnUST_MENUChanging(System.Nullable<bool> value);
    partial void OnUST_MENUChanged();
    partial void OnICERIKChanging(System.Nullable<bool> value);
    partial void OnICERIKChanged();
    partial void OnSAYFA_NOChanging(System.Nullable<int> value);
    partial void OnSAYFA_NOChanged();
    #endregion
		
		public KATEGORILER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KATEGORI_ADI", DbType="VarChar(50)")]
		public string KATEGORI_ADI
		{
			get
			{
				return this._KATEGORI_ADI;
			}
			set
			{
				if ((this._KATEGORI_ADI != value))
				{
					this.OnKATEGORI_ADIChanging(value);
					this.SendPropertyChanging();
					this._KATEGORI_ADI = value;
					this.SendPropertyChanged("KATEGORI_ADI");
					this.OnKATEGORI_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UST_KATEGORI_ID", DbType="Int")]
		public System.Nullable<int> UST_KATEGORI_ID
		{
			get
			{
				return this._UST_KATEGORI_ID;
			}
			set
			{
				if ((this._UST_KATEGORI_ID != value))
				{
					this.OnUST_KATEGORI_IDChanging(value);
					this.SendPropertyChanging();
					this._UST_KATEGORI_ID = value;
					this.SendPropertyChanged("UST_KATEGORI_ID");
					this.OnUST_KATEGORI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURUM", DbType="Bit")]
		public System.Nullable<bool> DURUM
		{
			get
			{
				return this._DURUM;
			}
			set
			{
				if ((this._DURUM != value))
				{
					this.OnDURUMChanging(value);
					this.SendPropertyChanging();
					this._DURUM = value;
					this.SendPropertyChanged("DURUM");
					this.OnDURUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="VarChar(80)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SILME_IZNI", DbType="Bit")]
		public System.Nullable<bool> SILME_IZNI
		{
			get
			{
				return this._SILME_IZNI;
			}
			set
			{
				if ((this._SILME_IZNI != value))
				{
					this.OnSILME_IZNIChanging(value);
					this.SendPropertyChanging();
					this._SILME_IZNI = value;
					this.SendPropertyChanged("SILME_IZNI");
					this.OnSILME_IZNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIRA_NO", DbType="Int")]
		public System.Nullable<int> SIRA_NO
		{
			get
			{
				return this._SIRA_NO;
			}
			set
			{
				if ((this._SIRA_NO != value))
				{
					this.OnSIRA_NOChanging(value);
					this.SendPropertyChanging();
					this._SIRA_NO = value;
					this.SendPropertyChanged("SIRA_NO");
					this.OnSIRA_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UST_MENU", DbType="Bit")]
		public System.Nullable<bool> UST_MENU
		{
			get
			{
				return this._UST_MENU;
			}
			set
			{
				if ((this._UST_MENU != value))
				{
					this.OnUST_MENUChanging(value);
					this.SendPropertyChanging();
					this._UST_MENU = value;
					this.SendPropertyChanged("UST_MENU");
					this.OnUST_MENUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICERIK", DbType="Bit")]
		public System.Nullable<bool> ICERIK
		{
			get
			{
				return this._ICERIK;
			}
			set
			{
				if ((this._ICERIK != value))
				{
					this.OnICERIKChanging(value);
					this.SendPropertyChanging();
					this._ICERIK = value;
					this.SendPropertyChanged("ICERIK");
					this.OnICERIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAYFA_NO", DbType="Int")]
		public System.Nullable<int> SAYFA_NO
		{
			get
			{
				return this._SAYFA_NO;
			}
			set
			{
				if ((this._SAYFA_NO != value))
				{
					this.OnSAYFA_NOChanging(value);
					this.SendPropertyChanging();
					this._SAYFA_NO = value;
					this.SendPropertyChanged("SAYFA_NO");
					this.OnSAYFA_NOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KATILIMCI_GORUSLERI")]
	public partial class KATILIMCI_GORUSLERI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _AD_SOYAD;
		
		private string _EGITIM;
		
		private string _GORUS;
		
		private System.Nullable<System.DateTime> _TARIH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAD_SOYADChanging(string value);
    partial void OnAD_SOYADChanged();
    partial void OnEGITIMChanging(string value);
    partial void OnEGITIMChanged();
    partial void OnGORUSChanging(string value);
    partial void OnGORUSChanged();
    partial void OnTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnTARIHChanged();
    #endregion
		
		public KATILIMCI_GORUSLERI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AD_SOYAD", DbType="VarChar(150)")]
		public string AD_SOYAD
		{
			get
			{
				return this._AD_SOYAD;
			}
			set
			{
				if ((this._AD_SOYAD != value))
				{
					this.OnAD_SOYADChanging(value);
					this.SendPropertyChanging();
					this._AD_SOYAD = value;
					this.SendPropertyChanged("AD_SOYAD");
					this.OnAD_SOYADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EGITIM", DbType="VarChar(150)")]
		public string EGITIM
		{
			get
			{
				return this._EGITIM;
			}
			set
			{
				if ((this._EGITIM != value))
				{
					this.OnEGITIMChanging(value);
					this.SendPropertyChanging();
					this._EGITIM = value;
					this.SendPropertyChanged("EGITIM");
					this.OnEGITIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GORUS", DbType="VarChar(MAX)")]
		public string GORUS
		{
			get
			{
				return this._GORUS;
			}
			set
			{
				if ((this._GORUS != value))
				{
					this.OnGORUSChanging(value);
					this.SendPropertyChanging();
					this._GORUS = value;
					this.SendPropertyChanged("GORUS");
					this.OnGORUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARIH
		{
			get
			{
				return this._TARIH;
			}
			set
			{
				if ((this._TARIH != value))
				{
					this.OnTARIHChanging(value);
					this.SendPropertyChanging();
					this._TARIH = value;
					this.SendPropertyChanged("TARIH");
					this.OnTARIHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MANSET")]
	public partial class MANSET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _RESIM;
		
		private string _BASLIK;
		
		private string _ACIKLAMA;
		
		private string _URL;
		
		private System.Nullable<int> _SIRA_NO;
		
		private string _TITLE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRESIMChanging(string value);
    partial void OnRESIMChanged();
    partial void OnBASLIKChanging(string value);
    partial void OnBASLIKChanged();
    partial void OnACIKLAMAChanging(string value);
    partial void OnACIKLAMAChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnSIRA_NOChanging(System.Nullable<int> value);
    partial void OnSIRA_NOChanged();
    partial void OnTITLEChanging(string value);
    partial void OnTITLEChanged();
    #endregion
		
		public MANSET()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESIM", DbType="VarChar(50)")]
		public string RESIM
		{
			get
			{
				return this._RESIM;
			}
			set
			{
				if ((this._RESIM != value))
				{
					this.OnRESIMChanging(value);
					this.SendPropertyChanging();
					this._RESIM = value;
					this.SendPropertyChanged("RESIM");
					this.OnRESIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BASLIK", DbType="VarChar(150)")]
		public string BASLIK
		{
			get
			{
				return this._BASLIK;
			}
			set
			{
				if ((this._BASLIK != value))
				{
					this.OnBASLIKChanging(value);
					this.SendPropertyChanging();
					this._BASLIK = value;
					this.SendPropertyChanged("BASLIK");
					this.OnBASLIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="VarChar(350)")]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this.OnACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACIKLAMA = value;
					this.SendPropertyChanged("ACIKLAMA");
					this.OnACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="VarChar(250)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIRA_NO", DbType="Int")]
		public System.Nullable<int> SIRA_NO
		{
			get
			{
				return this._SIRA_NO;
			}
			set
			{
				if ((this._SIRA_NO != value))
				{
					this.OnSIRA_NOChanging(value);
					this.SendPropertyChanging();
					this._SIRA_NO = value;
					this.SendPropertyChanged("SIRA_NO");
					this.OnSIRA_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="VarChar(250)")]
		public string TITLE
		{
			get
			{
				return this._TITLE;
			}
			set
			{
				if ((this._TITLE != value))
				{
					this.OnTITLEChanging(value);
					this.SendPropertyChanging();
					this._TITLE = value;
					this.SendPropertyChanged("TITLE");
					this.OnTITLEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.REFERANSLAR")]
	public partial class REFERANSLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _BASLIK;
		
		private string _ACIKLAMA;
		
		private string _RESIM;
		
		private System.Nullable<int> _SIRA_NO;
		
		private string _TITLE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBASLIKChanging(string value);
    partial void OnBASLIKChanged();
    partial void OnACIKLAMAChanging(string value);
    partial void OnACIKLAMAChanged();
    partial void OnRESIMChanging(string value);
    partial void OnRESIMChanged();
    partial void OnSIRA_NOChanging(System.Nullable<int> value);
    partial void OnSIRA_NOChanged();
    partial void OnTITLEChanging(string value);
    partial void OnTITLEChanged();
    #endregion
		
		public REFERANSLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BASLIK", DbType="VarChar(150)")]
		public string BASLIK
		{
			get
			{
				return this._BASLIK;
			}
			set
			{
				if ((this._BASLIK != value))
				{
					this.OnBASLIKChanging(value);
					this.SendPropertyChanging();
					this._BASLIK = value;
					this.SendPropertyChanged("BASLIK");
					this.OnBASLIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="VarChar(MAX)")]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this.OnACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACIKLAMA = value;
					this.SendPropertyChanged("ACIKLAMA");
					this.OnACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESIM", DbType="VarChar(150)")]
		public string RESIM
		{
			get
			{
				return this._RESIM;
			}
			set
			{
				if ((this._RESIM != value))
				{
					this.OnRESIMChanging(value);
					this.SendPropertyChanging();
					this._RESIM = value;
					this.SendPropertyChanged("RESIM");
					this.OnRESIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIRA_NO", DbType="Int")]
		public System.Nullable<int> SIRA_NO
		{
			get
			{
				return this._SIRA_NO;
			}
			set
			{
				if ((this._SIRA_NO != value))
				{
					this.OnSIRA_NOChanging(value);
					this.SendPropertyChanging();
					this._SIRA_NO = value;
					this.SendPropertyChanged("SIRA_NO");
					this.OnSIRA_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="VarChar(250)")]
		public string TITLE
		{
			get
			{
				return this._TITLE;
			}
			set
			{
				if ((this._TITLE != value))
				{
					this.OnTITLEChanging(value);
					this.SendPropertyChanging();
					this._TITLE = value;
					this.SendPropertyChanged("TITLE");
					this.OnTITLEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RESIM_AYAR")]
	public partial class RESIM_AYAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _MANSET_W;
		
		private System.Nullable<int> _MANSET_H;
		
		private System.Nullable<int> _GALERI_K_W;
		
		private System.Nullable<int> _GALERI_K_H;
		
		private System.Nullable<int> _HABER_K_W;
		
		private System.Nullable<int> _HABER_K_H;
		
		private System.Nullable<int> _REFERANS_K_W;
		
		private System.Nullable<int> _REFERANS_K_H;
		
		private System.Nullable<int> _LOGO_W;
		
		private System.Nullable<int> _GALERI_B_W;
		
		private System.Nullable<int> _GALERI_B_H;
		
		private System.Nullable<int> _HABER_B_W;
		
		private System.Nullable<int> _HABER_B_H;
		
		private System.Nullable<int> _REFERANS_B_W;
		
		private System.Nullable<int> _REFERANS_B_H;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMANSET_WChanging(System.Nullable<int> value);
    partial void OnMANSET_WChanged();
    partial void OnMANSET_HChanging(System.Nullable<int> value);
    partial void OnMANSET_HChanged();
    partial void OnGALERI_K_WChanging(System.Nullable<int> value);
    partial void OnGALERI_K_WChanged();
    partial void OnGALERI_K_HChanging(System.Nullable<int> value);
    partial void OnGALERI_K_HChanged();
    partial void OnHABER_K_WChanging(System.Nullable<int> value);
    partial void OnHABER_K_WChanged();
    partial void OnHABER_K_HChanging(System.Nullable<int> value);
    partial void OnHABER_K_HChanged();
    partial void OnREFERANS_K_WChanging(System.Nullable<int> value);
    partial void OnREFERANS_K_WChanged();
    partial void OnREFERANS_K_HChanging(System.Nullable<int> value);
    partial void OnREFERANS_K_HChanged();
    partial void OnLOGO_WChanging(System.Nullable<int> value);
    partial void OnLOGO_WChanged();
    partial void OnGALERI_B_WChanging(System.Nullable<int> value);
    partial void OnGALERI_B_WChanged();
    partial void OnGALERI_B_HChanging(System.Nullable<int> value);
    partial void OnGALERI_B_HChanged();
    partial void OnHABER_B_WChanging(System.Nullable<int> value);
    partial void OnHABER_B_WChanged();
    partial void OnHABER_B_HChanging(System.Nullable<int> value);
    partial void OnHABER_B_HChanged();
    partial void OnREFERANS_B_WChanging(System.Nullable<int> value);
    partial void OnREFERANS_B_WChanged();
    partial void OnREFERANS_B_HChanging(System.Nullable<int> value);
    partial void OnREFERANS_B_HChanged();
    #endregion
		
		public RESIM_AYAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANSET_W", DbType="Int")]
		public System.Nullable<int> MANSET_W
		{
			get
			{
				return this._MANSET_W;
			}
			set
			{
				if ((this._MANSET_W != value))
				{
					this.OnMANSET_WChanging(value);
					this.SendPropertyChanging();
					this._MANSET_W = value;
					this.SendPropertyChanged("MANSET_W");
					this.OnMANSET_WChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANSET_H", DbType="Int")]
		public System.Nullable<int> MANSET_H
		{
			get
			{
				return this._MANSET_H;
			}
			set
			{
				if ((this._MANSET_H != value))
				{
					this.OnMANSET_HChanging(value);
					this.SendPropertyChanging();
					this._MANSET_H = value;
					this.SendPropertyChanged("MANSET_H");
					this.OnMANSET_HChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GALERI_K_W", DbType="Int")]
		public System.Nullable<int> GALERI_K_W
		{
			get
			{
				return this._GALERI_K_W;
			}
			set
			{
				if ((this._GALERI_K_W != value))
				{
					this.OnGALERI_K_WChanging(value);
					this.SendPropertyChanging();
					this._GALERI_K_W = value;
					this.SendPropertyChanged("GALERI_K_W");
					this.OnGALERI_K_WChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GALERI_K_H", DbType="Int")]
		public System.Nullable<int> GALERI_K_H
		{
			get
			{
				return this._GALERI_K_H;
			}
			set
			{
				if ((this._GALERI_K_H != value))
				{
					this.OnGALERI_K_HChanging(value);
					this.SendPropertyChanging();
					this._GALERI_K_H = value;
					this.SendPropertyChanged("GALERI_K_H");
					this.OnGALERI_K_HChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABER_K_W", DbType="Int")]
		public System.Nullable<int> HABER_K_W
		{
			get
			{
				return this._HABER_K_W;
			}
			set
			{
				if ((this._HABER_K_W != value))
				{
					this.OnHABER_K_WChanging(value);
					this.SendPropertyChanging();
					this._HABER_K_W = value;
					this.SendPropertyChanged("HABER_K_W");
					this.OnHABER_K_WChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABER_K_H", DbType="Int")]
		public System.Nullable<int> HABER_K_H
		{
			get
			{
				return this._HABER_K_H;
			}
			set
			{
				if ((this._HABER_K_H != value))
				{
					this.OnHABER_K_HChanging(value);
					this.SendPropertyChanging();
					this._HABER_K_H = value;
					this.SendPropertyChanged("HABER_K_H");
					this.OnHABER_K_HChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REFERANS_K_W", DbType="Int")]
		public System.Nullable<int> REFERANS_K_W
		{
			get
			{
				return this._REFERANS_K_W;
			}
			set
			{
				if ((this._REFERANS_K_W != value))
				{
					this.OnREFERANS_K_WChanging(value);
					this.SendPropertyChanging();
					this._REFERANS_K_W = value;
					this.SendPropertyChanged("REFERANS_K_W");
					this.OnREFERANS_K_WChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REFERANS_K_H", DbType="Int")]
		public System.Nullable<int> REFERANS_K_H
		{
			get
			{
				return this._REFERANS_K_H;
			}
			set
			{
				if ((this._REFERANS_K_H != value))
				{
					this.OnREFERANS_K_HChanging(value);
					this.SendPropertyChanging();
					this._REFERANS_K_H = value;
					this.SendPropertyChanged("REFERANS_K_H");
					this.OnREFERANS_K_HChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGO_W", DbType="Int")]
		public System.Nullable<int> LOGO_W
		{
			get
			{
				return this._LOGO_W;
			}
			set
			{
				if ((this._LOGO_W != value))
				{
					this.OnLOGO_WChanging(value);
					this.SendPropertyChanging();
					this._LOGO_W = value;
					this.SendPropertyChanged("LOGO_W");
					this.OnLOGO_WChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GALERI_B_W", DbType="Int")]
		public System.Nullable<int> GALERI_B_W
		{
			get
			{
				return this._GALERI_B_W;
			}
			set
			{
				if ((this._GALERI_B_W != value))
				{
					this.OnGALERI_B_WChanging(value);
					this.SendPropertyChanging();
					this._GALERI_B_W = value;
					this.SendPropertyChanged("GALERI_B_W");
					this.OnGALERI_B_WChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GALERI_B_H", DbType="Int")]
		public System.Nullable<int> GALERI_B_H
		{
			get
			{
				return this._GALERI_B_H;
			}
			set
			{
				if ((this._GALERI_B_H != value))
				{
					this.OnGALERI_B_HChanging(value);
					this.SendPropertyChanging();
					this._GALERI_B_H = value;
					this.SendPropertyChanged("GALERI_B_H");
					this.OnGALERI_B_HChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABER_B_W", DbType="Int")]
		public System.Nullable<int> HABER_B_W
		{
			get
			{
				return this._HABER_B_W;
			}
			set
			{
				if ((this._HABER_B_W != value))
				{
					this.OnHABER_B_WChanging(value);
					this.SendPropertyChanging();
					this._HABER_B_W = value;
					this.SendPropertyChanged("HABER_B_W");
					this.OnHABER_B_WChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HABER_B_H", DbType="Int")]
		public System.Nullable<int> HABER_B_H
		{
			get
			{
				return this._HABER_B_H;
			}
			set
			{
				if ((this._HABER_B_H != value))
				{
					this.OnHABER_B_HChanging(value);
					this.SendPropertyChanging();
					this._HABER_B_H = value;
					this.SendPropertyChanged("HABER_B_H");
					this.OnHABER_B_HChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REFERANS_B_W", DbType="Int")]
		public System.Nullable<int> REFERANS_B_W
		{
			get
			{
				return this._REFERANS_B_W;
			}
			set
			{
				if ((this._REFERANS_B_W != value))
				{
					this.OnREFERANS_B_WChanging(value);
					this.SendPropertyChanging();
					this._REFERANS_B_W = value;
					this.SendPropertyChanged("REFERANS_B_W");
					this.OnREFERANS_B_WChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REFERANS_B_H", DbType="Int")]
		public System.Nullable<int> REFERANS_B_H
		{
			get
			{
				return this._REFERANS_B_H;
			}
			set
			{
				if ((this._REFERANS_B_H != value))
				{
					this.OnREFERANS_B_HChanging(value);
					this.SendPropertyChanging();
					this._REFERANS_B_H = value;
					this.SendPropertyChanged("REFERANS_B_H");
					this.OnREFERANS_B_HChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SITE_BILGILERI")]
	public partial class SITE_BILGILERI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _SLOGAN;
		
		private string _LOGO;
		
		private string _COPH;
		
		private string _DOMAIN;
		
		private System.Nullable<bool> _ACILIS_MESAJI_DURUM;
		
		private string _ACILIS_MESAJI;
		
		private string _TEMA;
		
		private string _BG_COLOR;
		
		private string _BG_IMG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSLOGANChanging(string value);
    partial void OnSLOGANChanged();
    partial void OnLOGOChanging(string value);
    partial void OnLOGOChanged();
    partial void OnCOPHChanging(string value);
    partial void OnCOPHChanged();
    partial void OnDOMAINChanging(string value);
    partial void OnDOMAINChanged();
    partial void OnACILIS_MESAJI_DURUMChanging(System.Nullable<bool> value);
    partial void OnACILIS_MESAJI_DURUMChanged();
    partial void OnACILIS_MESAJIChanging(string value);
    partial void OnACILIS_MESAJIChanged();
    partial void OnTEMAChanging(string value);
    partial void OnTEMAChanged();
    partial void OnBG_COLORChanging(string value);
    partial void OnBG_COLORChanged();
    partial void OnBG_IMGChanging(string value);
    partial void OnBG_IMGChanged();
    #endregion
		
		public SITE_BILGILERI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLOGAN", DbType="VarChar(50)")]
		public string SLOGAN
		{
			get
			{
				return this._SLOGAN;
			}
			set
			{
				if ((this._SLOGAN != value))
				{
					this.OnSLOGANChanging(value);
					this.SendPropertyChanging();
					this._SLOGAN = value;
					this.SendPropertyChanged("SLOGAN");
					this.OnSLOGANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGO", DbType="VarChar(50)")]
		public string LOGO
		{
			get
			{
				return this._LOGO;
			}
			set
			{
				if ((this._LOGO != value))
				{
					this.OnLOGOChanging(value);
					this.SendPropertyChanging();
					this._LOGO = value;
					this.SendPropertyChanged("LOGO");
					this.OnLOGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COPH", DbType="VarChar(150)")]
		public string COPH
		{
			get
			{
				return this._COPH;
			}
			set
			{
				if ((this._COPH != value))
				{
					this.OnCOPHChanging(value);
					this.SendPropertyChanging();
					this._COPH = value;
					this.SendPropertyChanged("COPH");
					this.OnCOPHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMAIN", DbType="VarChar(50)")]
		public string DOMAIN
		{
			get
			{
				return this._DOMAIN;
			}
			set
			{
				if ((this._DOMAIN != value))
				{
					this.OnDOMAINChanging(value);
					this.SendPropertyChanging();
					this._DOMAIN = value;
					this.SendPropertyChanged("DOMAIN");
					this.OnDOMAINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACILIS_MESAJI_DURUM", DbType="Bit")]
		public System.Nullable<bool> ACILIS_MESAJI_DURUM
		{
			get
			{
				return this._ACILIS_MESAJI_DURUM;
			}
			set
			{
				if ((this._ACILIS_MESAJI_DURUM != value))
				{
					this.OnACILIS_MESAJI_DURUMChanging(value);
					this.SendPropertyChanging();
					this._ACILIS_MESAJI_DURUM = value;
					this.SendPropertyChanged("ACILIS_MESAJI_DURUM");
					this.OnACILIS_MESAJI_DURUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACILIS_MESAJI", DbType="VarChar(MAX)")]
		public string ACILIS_MESAJI
		{
			get
			{
				return this._ACILIS_MESAJI;
			}
			set
			{
				if ((this._ACILIS_MESAJI != value))
				{
					this.OnACILIS_MESAJIChanging(value);
					this.SendPropertyChanging();
					this._ACILIS_MESAJI = value;
					this.SendPropertyChanged("ACILIS_MESAJI");
					this.OnACILIS_MESAJIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMA", DbType="VarChar(150)")]
		public string TEMA
		{
			get
			{
				return this._TEMA;
			}
			set
			{
				if ((this._TEMA != value))
				{
					this.OnTEMAChanging(value);
					this.SendPropertyChanging();
					this._TEMA = value;
					this.SendPropertyChanged("TEMA");
					this.OnTEMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BG_COLOR", DbType="VarChar(150)")]
		public string BG_COLOR
		{
			get
			{
				return this._BG_COLOR;
			}
			set
			{
				if ((this._BG_COLOR != value))
				{
					this.OnBG_COLORChanging(value);
					this.SendPropertyChanging();
					this._BG_COLOR = value;
					this.SendPropertyChanged("BG_COLOR");
					this.OnBG_COLORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BG_IMG", DbType="VarChar(150)")]
		public string BG_IMG
		{
			get
			{
				return this._BG_IMG;
			}
			set
			{
				if ((this._BG_IMG != value))
				{
					this.OnBG_IMGChanging(value);
					this.SendPropertyChanging();
					this._BG_IMG = value;
					this.SendPropertyChanged("BG_IMG");
					this.OnBG_IMGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SOSYAL_MEDYA")]
	public partial class SOSYAL_MEDYA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FACEBOOK;
		
		private string _TWITTER;
		
		private string _GOOGLE;
		
		private string _YOUTUBE;
		
		private string _BEHANCE;
		
		private string _INSTAGRAM;
		
		private string _DIGER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFACEBOOKChanging(string value);
    partial void OnFACEBOOKChanged();
    partial void OnTWITTERChanging(string value);
    partial void OnTWITTERChanged();
    partial void OnGOOGLEChanging(string value);
    partial void OnGOOGLEChanged();
    partial void OnYOUTUBEChanging(string value);
    partial void OnYOUTUBEChanged();
    partial void OnBEHANCEChanging(string value);
    partial void OnBEHANCEChanged();
    partial void OnINSTAGRAMChanging(string value);
    partial void OnINSTAGRAMChanged();
    partial void OnDIGERChanging(string value);
    partial void OnDIGERChanged();
    #endregion
		
		public SOSYAL_MEDYA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FACEBOOK", DbType="VarChar(500)")]
		public string FACEBOOK
		{
			get
			{
				return this._FACEBOOK;
			}
			set
			{
				if ((this._FACEBOOK != value))
				{
					this.OnFACEBOOKChanging(value);
					this.SendPropertyChanging();
					this._FACEBOOK = value;
					this.SendPropertyChanged("FACEBOOK");
					this.OnFACEBOOKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TWITTER", DbType="VarChar(500)")]
		public string TWITTER
		{
			get
			{
				return this._TWITTER;
			}
			set
			{
				if ((this._TWITTER != value))
				{
					this.OnTWITTERChanging(value);
					this.SendPropertyChanging();
					this._TWITTER = value;
					this.SendPropertyChanged("TWITTER");
					this.OnTWITTERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOOGLE", DbType="VarChar(500)")]
		public string GOOGLE
		{
			get
			{
				return this._GOOGLE;
			}
			set
			{
				if ((this._GOOGLE != value))
				{
					this.OnGOOGLEChanging(value);
					this.SendPropertyChanging();
					this._GOOGLE = value;
					this.SendPropertyChanged("GOOGLE");
					this.OnGOOGLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YOUTUBE", DbType="VarChar(500)")]
		public string YOUTUBE
		{
			get
			{
				return this._YOUTUBE;
			}
			set
			{
				if ((this._YOUTUBE != value))
				{
					this.OnYOUTUBEChanging(value);
					this.SendPropertyChanging();
					this._YOUTUBE = value;
					this.SendPropertyChanged("YOUTUBE");
					this.OnYOUTUBEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEHANCE", DbType="VarChar(500)")]
		public string BEHANCE
		{
			get
			{
				return this._BEHANCE;
			}
			set
			{
				if ((this._BEHANCE != value))
				{
					this.OnBEHANCEChanging(value);
					this.SendPropertyChanging();
					this._BEHANCE = value;
					this.SendPropertyChanged("BEHANCE");
					this.OnBEHANCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSTAGRAM", DbType="VarChar(500)")]
		public string INSTAGRAM
		{
			get
			{
				return this._INSTAGRAM;
			}
			set
			{
				if ((this._INSTAGRAM != value))
				{
					this.OnINSTAGRAMChanging(value);
					this.SendPropertyChanging();
					this._INSTAGRAM = value;
					this.SendPropertyChanged("INSTAGRAM");
					this.OnINSTAGRAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIGER", DbType="VarChar(500)")]
		public string DIGER
		{
			get
			{
				return this._DIGER;
			}
			set
			{
				if ((this._DIGER != value))
				{
					this.OnDIGERChanging(value);
					this.SendPropertyChanging();
					this._DIGER = value;
					this.SendPropertyChanged("DIGER");
					this.OnDIGERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TEMALAR")]
	public partial class TEMALAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TEMA_ADI;
		
		private string _IMG;
		
		private string _ACIKLAMA;
		
		private System.Nullable<bool> _DURUM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTEMA_ADIChanging(string value);
    partial void OnTEMA_ADIChanged();
    partial void OnIMGChanging(string value);
    partial void OnIMGChanged();
    partial void OnACIKLAMAChanging(string value);
    partial void OnACIKLAMAChanged();
    partial void OnDURUMChanging(System.Nullable<bool> value);
    partial void OnDURUMChanged();
    #endregion
		
		public TEMALAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMA_ADI", DbType="VarChar(50)")]
		public string TEMA_ADI
		{
			get
			{
				return this._TEMA_ADI;
			}
			set
			{
				if ((this._TEMA_ADI != value))
				{
					this.OnTEMA_ADIChanging(value);
					this.SendPropertyChanging();
					this._TEMA_ADI = value;
					this.SendPropertyChanged("TEMA_ADI");
					this.OnTEMA_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMG", DbType="VarChar(50)")]
		public string IMG
		{
			get
			{
				return this._IMG;
			}
			set
			{
				if ((this._IMG != value))
				{
					this.OnIMGChanging(value);
					this.SendPropertyChanging();
					this._IMG = value;
					this.SendPropertyChanged("IMG");
					this.OnIMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="VarChar(MAX)")]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this.OnACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACIKLAMA = value;
					this.SendPropertyChanged("ACIKLAMA");
					this.OnACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURUM", DbType="Bit")]
		public System.Nullable<bool> DURUM
		{
			get
			{
				return this._DURUM;
			}
			set
			{
				if ((this._DURUM != value))
				{
					this.OnDURUMChanging(value);
					this.SendPropertyChanging();
					this._DURUM = value;
					this.SendPropertyChanged("DURUM");
					this.OnDURUMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.URUN_KATEGORILERI")]
	public partial class URUN_KATEGORILERI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KATEGORI;
		
		private string _DESCRIPTION;
		
		private string _KEYWORDS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKATEGORIChanging(string value);
    partial void OnKATEGORIChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnKEYWORDSChanging(string value);
    partial void OnKEYWORDSChanged();
    #endregion
		
		public URUN_KATEGORILERI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KATEGORI", DbType="VarChar(50)")]
		public string KATEGORI
		{
			get
			{
				return this._KATEGORI;
			}
			set
			{
				if ((this._KATEGORI != value))
				{
					this.OnKATEGORIChanging(value);
					this.SendPropertyChanging();
					this._KATEGORI = value;
					this.SendPropertyChanged("KATEGORI");
					this.OnKATEGORIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="VarChar(250)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEYWORDS", DbType="VarChar(250)")]
		public string KEYWORDS
		{
			get
			{
				return this._KEYWORDS;
			}
			set
			{
				if ((this._KEYWORDS != value))
				{
					this.OnKEYWORDSChanging(value);
					this.SendPropertyChanging();
					this._KEYWORDS = value;
					this.SendPropertyChanged("KEYWORDS");
					this.OnKEYWORDSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.URUNLER")]
	public partial class URUNLER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _KAT_ID;
		
		private string _URUN_ADI;
		
		private string _ACIKLAMA;
		
		private string _RESIM;
		
		private System.Nullable<System.DateTime> _EK_TARIHI;
		
		private string _FIYAT;
		
		private string _KEYWORDS;
		
		private string _DESCRIPTION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKAT_IDChanging(System.Nullable<int> value);
    partial void OnKAT_IDChanged();
    partial void OnURUN_ADIChanging(string value);
    partial void OnURUN_ADIChanged();
    partial void OnACIKLAMAChanging(string value);
    partial void OnACIKLAMAChanged();
    partial void OnRESIMChanging(string value);
    partial void OnRESIMChanged();
    partial void OnEK_TARIHIChanging(System.Nullable<System.DateTime> value);
    partial void OnEK_TARIHIChanged();
    partial void OnFIYATChanging(string value);
    partial void OnFIYATChanged();
    partial void OnKEYWORDSChanging(string value);
    partial void OnKEYWORDSChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    #endregion
		
		public URUNLER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KAT_ID", DbType="Int")]
		public System.Nullable<int> KAT_ID
		{
			get
			{
				return this._KAT_ID;
			}
			set
			{
				if ((this._KAT_ID != value))
				{
					this.OnKAT_IDChanging(value);
					this.SendPropertyChanging();
					this._KAT_ID = value;
					this.SendPropertyChanged("KAT_ID");
					this.OnKAT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URUN_ADI", DbType="VarChar(150)")]
		public string URUN_ADI
		{
			get
			{
				return this._URUN_ADI;
			}
			set
			{
				if ((this._URUN_ADI != value))
				{
					this.OnURUN_ADIChanging(value);
					this.SendPropertyChanging();
					this._URUN_ADI = value;
					this.SendPropertyChanged("URUN_ADI");
					this.OnURUN_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="VarChar(MAX)")]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this.OnACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACIKLAMA = value;
					this.SendPropertyChanged("ACIKLAMA");
					this.OnACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESIM", DbType="VarChar(50)")]
		public string RESIM
		{
			get
			{
				return this._RESIM;
			}
			set
			{
				if ((this._RESIM != value))
				{
					this.OnRESIMChanging(value);
					this.SendPropertyChanging();
					this._RESIM = value;
					this.SendPropertyChanged("RESIM");
					this.OnRESIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EK_TARIHI", DbType="DateTime")]
		public System.Nullable<System.DateTime> EK_TARIHI
		{
			get
			{
				return this._EK_TARIHI;
			}
			set
			{
				if ((this._EK_TARIHI != value))
				{
					this.OnEK_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._EK_TARIHI = value;
					this.SendPropertyChanged("EK_TARIHI");
					this.OnEK_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIYAT", DbType="VarChar(50)")]
		public string FIYAT
		{
			get
			{
				return this._FIYAT;
			}
			set
			{
				if ((this._FIYAT != value))
				{
					this.OnFIYATChanging(value);
					this.SendPropertyChanging();
					this._FIYAT = value;
					this.SendPropertyChanged("FIYAT");
					this.OnFIYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEYWORDS", DbType="VarChar(250)")]
		public string KEYWORDS
		{
			get
			{
				return this._KEYWORDS;
			}
			set
			{
				if ((this._KEYWORDS != value))
				{
					this.OnKEYWORDSChanging(value);
					this.SendPropertyChanging();
					this._KEYWORDS = value;
					this.SendPropertyChanged("KEYWORDS");
					this.OnKEYWORDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="VarChar(250)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
